name: Build and Deploy Package

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  release:
    types:
      - created

env:
  NODE_VERSION: 14

jobs:
  build:
    name: "🚀Build and Publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: borales/actions-yarn@v3.0.0
      - run: yarn install --frozen-lockfile
      - run: yarn tailwind
      - run: yarn build
      - name: Publish to GitHub Packages
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
          scope: "@octadesk-tech"
      - uses: borales/actions-yarn@v3.0.0
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
